### ISSUE TITLE
(Request) Why not use SteamCMD for fetching Server files instead of GitHub?

### ISSUE THREAD

**Issue by raykai** [Uuvana-Studios/longvinter-windows-server#1]
I think it would be best to host the files with SteamCMD [https://developer.valvesoftware.com/wiki/SteamCMD](https://developer.valvesoftware.com/wiki/SteamCMD) so we can use a bat file to pull the updates. Just like most other games that have dedicated serves on steam.

Needing to install additional software to download/update the server is a pain and is even more problematic on shared servers. Plus we need to run more than one command. 

Many of us run many game servers, if all steam games that have dedicated servers would ask us to all use different methods and software to get updates ... it would be chaotic.

I don't think many of us feel like going back to the guide to get the commands to update the server every time we need to. 

Plz, consider using the SteamCMD way of fetching updates from steam for the dedicated server.

**Comment by gui710** [comment]
You can already use a bat file to fetch the servers updates, I even made a bat file and posted it on #server-admins on Discord.

**Comment by raykai** [comment]
> You can already use a bat file to fetch the servers updates, I even made a bat file and posted it on #server-admins on Discord.

Thanks.

**Comment by JoshBleggi** [comment]
Can we reopen this issue? SteamCMD is one of the most common methods of managing dedicated servers for Steam Games. I see this as a must have at some point in the future.
