### ISSUE TITLE
Failed to Open Descriptor File

### ISSUE THREAD

**Issue by applemiku** [Uuvana-Studios/longvinter-windows-server#3]
![](https://p.sda1.dev/5/d6625a8f9eba33ff958ce31f5f6e12ab/1.jpg)
Hi,I try to open it it gives me this error. What should I do? Thanks for help!

Windows Server 2019

**Comment by Jalsson** [comment]
This usually appears if you have not downloaded the [GIT LFS](https://git-lfs.github.com/).
Try installing that and then give it another go!

**Comment by laboriens** [comment]
thank you
