### ISSUE TITLE
dock so full of unmoving characters, that I cannot do anything when I spawn

### ISSUE THREAD

**Issue by MikaylaLoud** [Uuvana-Studios/longvinter-windows-server#5]
I log onto the server and there is a wall of characters, bots or unmoving players?, stuck to the dock and I cannot go anywhere. I can't get around or move them, I start with only 100mk in my inv. I would just like it fixed because the game has a lot of potential, and this makes playing impossible. thanks in advance!

**Comment by sirNugg3ts** [comment]
This is not a bug with the server, please issue a bug report in windows client and with the appropriate template
